name: Build macOS Executable

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # Replace with your Python version

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile --windowed hehe.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hehe
          path: dist/
